name: Android Github Action
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Android Github Action
        uses: vukan-markovic/Github-Android-Action@1.2
        with:
          api-key: ${{ secrets.GOOGLE_PLAY_API_KEY }}
          app: app/build/outputs/apk/debug/app-debug.apk
          track: internal
