name: Run Android App Unit Tests
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and run unit tests
        run: ./gradlew clean connectedCheck
